apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "trace_id\":\"([a-f0-9]+)\""
          name: TraceID
          url: "$${__value.raw}"
        - datasourceUid: jaeger
          matcherRegex: "trace_id\":\"([a-f0-9]+)\""
          name: View in Jaeger
          url: "http://jaeger:16686/trace/$${__value.raw}"
