apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  containers:
    - name: node
      image: node:24-slim
      command: ['cat']
      tty: true
    - name: buildkit
      image: moby/buildkit:v0.29.0-rootless
      securityContext:
        privileged: true
      command: ['sh', '-c', 'buildkitd --addr unix:///run/buildkit/buildkitd.sock']
      volumeMounts:
        - name: buildkit-socket
          mountPath: /run/buildkit
  volumes:
    - name: buildkit-socket
      emptyDir: {}
